id: A5C168120
title: A Method of Confessing and Pledging through the Four Powers
type: translation
pechas:
- ID84A0812
- IA26A8F65
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:57:47.051769
  last_modified_at: 2023-01-04 12:57:47.051794
  collections:
  - Lobzang Chökyi Gyaltsen
  - Works of Tibetan Masters
alignment_to_base:
  ID84A0812/DBF3: 11FB
  IA26A8F65/0714: 11FB
